//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado_muudel_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opilane
    {
        public int opilaneId { get; set; }
        public string eesnimi { get; set; }
        public string perenimi { get; set; }
        public string synniaeg { get; set; }
        public Nullable<decimal> keskmine_hinne { get; set; }
    
        public virtual Ryhm Ryhm { get; set; }
    }
}
